export interface Employee {
    sno:string;
    firstName:string;
    lastName:string;
    emailId:string;
    expDepartment:string;
    primarySkill:string;
    status:string;
    billable:boolean;
    expJoinDate:Date;
    expSeparatedDate:Date;
    joinDate:Date;
    gender:string;
    department:string;
    cAddress:string;
    cCountry:string;
    cState:string;
    cCity:string;
    cZipCode:number;
    checking:boolean;
    pAddress:string;
    pCountry:string;
    pState:string;
    pCity:string;
    pZipCode:number;
    roles:any;
    bloodGroup:string;
    panNo:number;
    adharNo:number;
    phoneNum:number;
    maritalStatus:string,
    anniversaryDate:Date
    
}
